### ISSUE TITLE
Frage zu deiner Speedcam

### ISSUE THREAD

**Issue by fiesi** [benstrobel/altv-speedcam#1]
Funktioniert es noch?

Irgendwie, passiert bei E nichts.
Oder muss noch etwas eingestellt werden damit man eine Platzieren kann und so?

**Comment by FDiskas** [comment]
on client.js add something like. Not sure how to remove or reuse same key for adding and using speedcam
```
alt.on('keydown', (key) => {
  if (key === 69) // E
  placeSpeedCam();
})

alt.on('keydown', (key) => {
  if (key === 82) // R
  useButtonFunction();
})
```

**Comment by benstrobel** [comment]
Sorry for the late answer, as FDiskas pointed out you need to implement the part where your players either place, remove or use a sppedcam yourself. This is intentionally left out so anyone who wants to use this ressource can call the methods of this ressource from potential item or other systems. To do so just call the exported functions of the client.
"Using" the speedcam subscribes the player to messages of the speedcam, so they get notified when a vehicle is deteced
